name: Build Image

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64/v8
          - linux/i386
          - linux/ppc64le
          - linux/riscv64

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Build Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: false
          pull: true
          platforms: ${{ matrix.platform }}
          tags: nativebuilds/builder-image:latest

  build-all:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Build Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: false
          pull: true
          platforms: linux/amd64,linux/arm,linux/arm/v6,linux/arm/v7,linux/arm64,linux/arm64/v8,linux/i386,linux/ppc64le,linux/riscv64
          tags: nativebuilds/builder-image:latest
